# Generated by Django 3.1.7 on 2021-06-30 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default=False, upload_to='images/%y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='post',
            name='secondary_image',
            field=models.ImageField(default=False, upload_to='secondary/images/%y/%m/%d/'),
        ),
    ]
